const STORAGE_KEY='palne_plus_v4'; const OLD_KEYS=['palne_plus_v3','palne_plus_v2','palne_plus_v1'];
const today=()=>new Date().toISOString().slice(0,10); const uid=()=>Math.random().toString(36).slice(2)+Date.now().toString(36); const clone=o=>JSON.parse(JSON.stringify(o));
const parseNum=v=>{if(v===null||v===undefined)return 0; const s=String(v).replace(/\s/g,'').replace(',','.').replace(/[^0-9.\-]/g,''); const n=parseFloat(s); return isNaN(n)?0:n};
const round1=n=>Math.round(parseNum(n)*10)/10, round2=n=>Math.round(parseNum(n)*100)/100;
const fmt=(n,d=1)=>Number(parseNum(n)).toLocaleString('uk-UA',{minimumFractionDigits:d,maximumFractionDigits:d}); const money=n=>Number(parseNum(n)).toLocaleString('uk-UA',{maximumFractionDigits:0})+' грн'; const mileageFmt=n=>parseNum(n)?Math.round(parseNum(n)).toLocaleString('uk-UA').replace(/,/g,' '):'0';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const help=t=>`<button type="button" class="help-icon" data-tip="${esc(t)}">?</button>`;
const labelHelp=(text,tip)=>`<label class="label-with-help">${esc(text)} ${help(tip)}</label>`;
const dateLabel=d=>new Date(d+'T12:00:00').toLocaleDateString('uk-UA',{weekday:'long',day:'2-digit',month:'long',year:'numeric'});
const defaults={theme:'light',activeTab:'gas',statsPeriod:'week',statsFrom:today(),statsTo:today(),base:{gasLiters:0,petrolLiters:0,odometer:0},petrolLevels:[],settings:{gasCity:10,gasRoad:8,gasTankCapacity:32,petrolTankCapacity:50,gasWarningPercent:20,gasWarningKm:50,lastGasPrice:40.9,lastPetrolPrice:58.9,dashboardMode:'city'},history:[],trips:[],corrections:[],calc:{price:40.9,segments:[],roundTrip:false,shared:false,passengers:1,includeDriver:true}};
const tabLabels={gas:'🛢️ Газ',petrol:'⛽ Бензин',calc:'🧮 Калькулятор',history:'📒 Історія',stats:'📊 Статистика',settings:'⚙️ Налашт.'};
let state=loadState(); let editingEntryId=null, editingTripId=null, editingCorrectionId=null, toastTimer=null, undoTimer=null;

function normalizeImportedState(imported){const source=imported?.data||imported||{}; const settings={...defaults.settings,...(source.settings||{})}; if(source.settings?.gasWorkingVolume&&!source.settings?.gasTankCapacity)settings.gasTankCapacity=source.settings.gasWorkingVolume; const trips=Array.isArray(source.trips)?source.trips:[]; const history=Array.isArray(source.history)?source.history:[]; const base={...defaults.base,...(source.base||{})}; if(!source.base){try{const legacy=legacyGasStats(source); base.gasLiters=round2(legacy.left); base.odometer=Math.round(legacy.currentMileage||suggestLegacyMileage(source)||0)}catch{} } return {...clone(defaults),...source,base,settings,calc:{...defaults.calc,...(source.calc||{}),segments:Array.isArray(source.calc?.segments)?source.calc.segments:[]},history:history.map(e=>({...e,id:e.id||uid(),comment:e.comment||'',date:e.date||today(),createdAt:e.createdAt||new Date().toISOString(),updatedAt:e.updatedAt||e.createdAt||new Date().toISOString()})),trips:trips.map(t=>({...t,id:t.id||uid(),date:t.date||today(),comment:t.comment||'',createdAt:t.createdAt||new Date().toISOString(),updatedAt:t.updatedAt||t.createdAt||new Date().toISOString()})),corrections:Array.isArray(source.corrections)?source.corrections:[],petrolLevels:Array.isArray(source.petrolLevels)?source.petrolLevels:[]}}
const DB_NAME='palne-plus-db', DB_STORE='state', DB_KEY='main';
let _db=null;
function openDb(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=e=>e.target.result.createObjectStore(DB_STORE);r.onsuccess=e=>{_db=e.target.result;res(_db)};r.onerror=e=>rej(e.target.error)})}
function idbGet(){return new Promise((res,rej)=>{const tx=_db.transaction(DB_STORE,'readonly'),req=tx.objectStore(DB_STORE).get(DB_KEY);req.onsuccess=e=>res(e.target.result);req.onerror=e=>rej(e.target.error)})}
function idbSet(val){return new Promise((res,rej)=>{const tx=_db.transaction(DB_STORE,'readwrite'),req=tx.objectStore(DB_STORE).put(val,DB_KEY);req.onsuccess=()=>res();req.onerror=e=>rej(e.target.error)})}
function saveState(){idbSet(JSON.stringify(state)).catch(e=>console.error('IDB save error',e))}
function loadState(){return clone(defaults)}
async function initApp(){
  await openDb();
  let raw=null;
  try{raw=await idbGet()}catch(e){console.error(e)}
  if(!raw){
    for(const k of OLD_KEYS){const v=localStorage.getItem(k);if(v){raw=v;break}}
    if(!raw)raw=localStorage.getItem(STORAGE_KEY);
  }
  state=raw?normalizeImportedState(JSON.parse(raw)):clone(defaults);
  setTheme(state.theme||'light');render();setTab('gas');
}
function setTheme(t){state.theme=t;document.documentElement.classList.toggle('dark',t==='dark');document.getElementById('themeBtn').textContent=t==='dark'?'☀️':'🌙';saveState()} function setTab(t){state.activeTab=t;document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===t));document.querySelectorAll('.tab-page').forEach(p=>p.classList.add('hidden'));document.getElementById('tab-'+t).classList.remove('hidden');const lbl=document.getElementById('activeTabLabel');if(lbl)lbl.textContent=tabLabels[t]||'Меню';const panel=document.getElementById('menuPanel');if(panel)panel.classList.remove('open');syncUiChrome();saveState()}
function legacyGasStats(s){const settings={...defaults.settings,...(s.settings||{})}; const full=[...(s.history||[])].filter(e=>e.fuel==='gas'&&e.fullTank).sort((a,b)=>new Date(b.createdAt||b.date)-new Date(a.createdAt||a.date))[0]; const start=full?parseNum(full.liters)||parseNum(settings.gasWorkingVolume)||32:0; const startMileage=full?parseNum(full.mileage):0; const afterFull=(s.trips||[]).filter(t=>!full||new Date(t.createdAt||t.date)>new Date(full.createdAt||full.date)); const used=afterFull.reduce((a,t)=>a+parseNum(t.km)*(t.mode==='road'?parseNum(settings.gasRoad):parseNum(settings.gasCity))/100,0); const driven=afterFull.reduce((a,t)=>a+parseNum(t.km),0); return {left:Math.max(0,start-used),currentMileage:startMileage+driven}}
function suggestLegacyMileage(s){const a=[...(s.history||[]).map(e=>parseNum(e.mileage)),...(s.trips||[]).map(t=>parseNum(t.odometerAfter))].filter(Boolean); return a.length?Math.max(...a):0}
function allEventsAsc(){const ev=[...state.history.map(e=>({...e,type:'refuel'})),...state.trips.map(t=>({...t,type:'trip'})),...(state.corrections||[]).map(c=>({...c,type:'correction'}))]; return ev.sort((a,b)=>(a.date||'').localeCompare(b.date||'') || new Date(a.createdAt||0)-new Date(b.createdAt||0))}
function recompute(){let gas=parseNum(state.base?.gasLiters),petrol=parseNum(state.base?.petrolLiters),odo=parseNum(state.base?.odometer); const gs=Math.max(.1,parseNum(state.settings.gasCity)), gr=Math.max(.1,parseNum(state.settings.gasRoad)), gasCap=Math.max(.1,parseNum(state.settings.gasTankCapacity)), petCap=Math.max(.1,parseNum(state.settings.petrolTankCapacity)); const tripAfter={}; for(const e of allEventsAsc()){if(e.type==='refuel'){if(e.fuel==='gas'){gas=e.fullTank?gasCap:Math.min(gasCap,gas+parseNum(e.liters)); if(parseNum(e.price)>0){} } else {petrol=e.fullTank?petCap:Math.min(petCap,petrol+parseNum(e.liters))} if(parseNum(e.mileage)>0)odo=parseNum(e.mileage)} else if(e.type==='trip'){const km=parseNum(e.km); gas=Math.max(0,gas-km*(e.mode==='road'?gr:gs)/100); odo+=km; tripAfter[e.id]=Math.round(odo)} else if(e.type==='correction'){if(e.kind==='gas')gas=Math.max(0,Math.min(gasCap,parseNum(e.value))); if(e.kind==='petrol')petrol=Math.max(0,Math.min(petCap,parseNum(e.value))); if(e.kind==='odometer')odo=parseNum(e.value)}} return {gas:round2(gas),petrol:round2(petrol),odometer:Math.round(odo),tripAfter}}
function current(){return recompute()}
function odometerAtDate(date,skipCorrectionId=null){let odo=parseNum(state.base?.odometer); const events=allEventsAsc().filter(e=>!(e.type==='correction'&&e.id===skipCorrectionId)).filter(e=>(e.date||'')<=date); for(const e of events){if(e.type==='refuel'){if(parseNum(e.mileage)>0)odo=parseNum(e.mileage)} else if(e.type==='trip'){odo+=parseNum(e.km)} else if(e.type==='correction'&&e.kind==='odometer'){odo=parseNum(e.value)}} return Math.round(odo)}
function gasStats(){const c=current(), left=c.gas, cap=Math.max(.1,parseNum(state.settings.gasTankCapacity)), cityCons=Math.max(.1,parseNum(state.settings.gasCity)), roadCons=Math.max(.1,parseNum(state.settings.gasRoad)), price=parseNum(state.settings.lastGasPrice); const percent=Math.max(0,Math.min(100,left/cap*100)); const cityKm=left/cityCons*100, roadKm=left/roadCons*100; return {left,cap,percent,cityKm,roadKm,odometer:c.odometer,cityCost1:cityCons*price/100,roadCost1:roadCons*price/100,refuelCityAt:c.odometer+cityKm,refuelRoadAt:c.odometer+roadKm,warn:percent<=parseNum(state.settings.gasWarningPercent)||cityKm<=parseNum(state.settings.gasWarningKm)}}
function progressColor(percent){const p=Math.max(0,Math.min(100,percent)); if(p>=50)return '#22c55e'; if(p<=10){const t=p/10; return mix('#ef4444','#f59e0b',t)} const t=(p-10)/40; return mix('#f59e0b','#22c55e',t)} function mix(a,b,t){const ah=parseInt(a.slice(1),16),bh=parseInt(b.slice(1),16),ar=ah>>16&255,ag=ah>>8&255,ab=ah&255,br=bh>>16&255,bg=bh>>8&255,bb=bh&255; const r=Math.round(ar+(br-ar)*t),g=Math.round(ag+(bg-ag)*t),bl=Math.round(ab+(bb-ab)*t); return '#'+((1<<24)+(r<<16)+(g<<8)+bl).toString(16).slice(1)}


